### ISSUE TITLE
Tag/TagList: Add onBeforeRemove prop

### ISSUE THREAD

**Issue by Charca** [helpscout/hsds-react#280]
It'd be really nice if we could add an optional `onBeforeRemove` to the Tag and TagList components so we could only make the tag dissappear when/if the request to remove the tag actually resolves. With a feature like this we could sync up the tag being removed from different parts of the UI at the same time.

It would also be great to have an "out of the box" loading state where the delete cross icon is replaced by a spinner :)

**Comment by ItsJonQ** [comment]
@Charca OooOoo! Great ideas :D!!

**Comment by ItsJonQ** [comment]
@Charca Took a while, but we have this now 😅 

Example:

```jsx
onBeforeRemove = ({ id, value }) => {
  return new Promise(resolve => {
    console.log('REMOVING', id)
    setTimeout(() => {
      resolve()
    }, 500)
  })
}

...

<Tag onBeforeRemove={onBeforeRemove} />

// or with TagList
<TagList onBeforeRemove={onBeforeRemove}>
  <Tag />
  <Tag />
  <Tag />
</TagList>
```
