### ISSUE TITLE
pack/seed-button/_index not found when npm start command is executed

### ISSUE THREAD

**Issue by AngelMerinoB** [helpscout/hsds-react#551]
Hi,

i'm recently exploring open source projects and I tried to check hsds-react to hopefully help with some issues, but after installing it when `npm start` command is runned, it shows an error message like this: 

> ERROR in ./src/styles/blue.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js??ref--10-2!./src/styles/blue.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

> undefined
> ^
>       File to import not found or unreadable: pack/seed-button/_index.
>       in C:\Users\nobod\Documents\GitHub\Help Scout\hsds-react\src\styles\components\Button.scss (line 4, column 1)
>  @ ./src/styles/blue.scss 4:14-133 18:2-22:4 19:20-139
>  @ ./.storybook/config.js
>  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

Maybe it's related to some missing file. In fact, if we take a look at the path `src/styles/components` there is no `pack/` folder in it and the `Button.scss` in the same path is trying to import some files from it:

https://github.com/helpscout/hsds-react/blob/6e8b47e01a25ad517a1578d79bee9b67d3b53853/src/styles/components/Button.scss#L4-L6

Am I confusing some steps to install and run this repo or is it really an issue with a missing folder? 

Thank you guys, you look like a cool team btw!

**Comment by ItsJonQ** [comment]
@AngelMerinoB Hi there!

Thanks for reaching out!

> C:\Users\nobod\Documents\GitHub\Help Scout\hsds-react\src\styles\components\Button.scss 

Hmm! That's very interesting.

All you need to do is run `npm install` to get set up, then `npm start` to fire up Storybook. You shouldn't need to do anything else.

Would you be able to let me know what Node version you're on?
You should be able to find that out by running

```
node -v
```

To double check... would you be able to check your `node_modules` directory, to make sure

```
node_modules/seed-button
```

is there?

Also! What kind of machine are you on?

I typically work on a Mac. Once in a while, I'd pop on a Windows machine with Ubuntu installed. I haven't run into this issue before. I don't think anyone on our team has either.

> i'm recently exploring open source projects

That's awesome!

For some context, HSDS: React is something designed specifically for Help Scout. So it may not meet your needs. If you need a more generic React component library, I've personally had pretty good experience with Ant (https://ant.design/).

Thanks for commenting! Interested to hear your feedback.

**Comment by plbabin** [comment]
closing because SCSS was entirely removed in https://github.com/helpscout/hsds-react/tree/v3
