### ISSUE TITLE
data-cy selectors are wrong

### ISSUE THREAD

**Issue by ryan-mulrooney** [helpscout/hsds-react#595]
Recently cypress tests have been failing because the selectors we use have changed to something like `data-cy="propConnected(Heading)"` (usually they're `data-cy="greeter-new-button"`)

**Comment by ItsJonQ** [comment]
@ryan-mulrooney Thanks a bunch!! Will take care of this today! 💪

**Comment by ItsJonQ** [comment]
Making an update in Fancy:
https://github.com/helpscout/fancy/pull/45

Once that's merged. Will take care of that in HSDS: React. Then finally, in the app.

**Comment by ItsJonQ** [comment]
Something is up with the `data-cy` passing during the propConnect phase.

Alternative fix. Sanitize the namespace before passing it through.

If a `prop['data-cy']` is defined... and if there are HOC wrappers (e.g. `connected()`), unwrap it to use the base namespace.

Rough code idea:
```
const matches = namespace.replace('/\(|\)/g', '|').split('|').filter(n => n)
const sanitizedNamespace = matches[matches.length - 1]
```
