### ISSUE TITLE
Styled: Enhance with theme variables

### ISSUE THREAD

**Issue by ItsJonQ** [helpscout/hsds-react#601]
A really neat idea from https://baseweb.design/getting-started/installation/

```
import {styled} from 'baseui';

const Anchor = styled('a', ({$theme}) => ({
  color: $theme.colors.primary,
}));
```

Might need to enhance Fancy to allow for this pass through

**Comment by ItsJonQ** [comment]
Could also pass through other style utilities, like `rgba`.. or font utils. At the very least, having access to `getColor` would be nice

**Comment by ItsJonQ** [comment]
https://github.com/helpscout/fancy/pull/46

**Comment by tinkertrain** [comment]
Archiving
