### ISSUE TITLE
`closeOnBodyClick` doesn't seem to work for `Tooltip` / `Popover`

### ISSUE THREAD

**Issue by brettjonesdev** [helpscout/hsds-react#623]
We have a `closeOnBodyClick` prop that Tooltip / Popover are supposed to support, but it isn't working currently. `closeOnContentClick` works, but the body click does not. 

![demo](https://d2ddoduugvun08.cloudfront.net/items/2q432K1i0h1S0U1A1a2g/Screen%20Recording%202019-05-14%20at%2003.27%20PM.gif?X-CloudApp-Visitor-Id=84d63d0548cf1127177fc06997ae891f) 

FWIW I think we ought to make this option default to `true` while we're at it? Open to hearing reasons we might not want to though.

**Comment by ItsJonQ** [comment]
@brettjonesdev Thanks Brett! Working on this now!!
