### ISSUE TITLE
HSApp + Page.Actions (Sticky)

### ISSUE THREAD

**Issue by ItsJonQ** [helpscout/hsds-react#626]
![Screen Shot 2019-05-15 at 12 02 59 PM](https://user-images.githubusercontent.com/2322354/57790920-bc5af780-7709-11e9-97fd-7437b2f0065c.png)

Ooof!! Need to adjust the actions to better calculate it's (left) position, when rendered within an HS App shell.

**Comment by tinkertrain** [comment]
HS App shell was removed in v3
