### ISSUE TITLE
Component: Custom radio check icon is too small

### ISSUE THREAD

**Issue by jaredmcdaniel** [helpscout/hsds-react#646]
## Problem
Noticed in Beacon modes that the check icon on the custom radio component is too small.

![squint](https://user-images.githubusercontent.com/2151364/59715187-f02daf00-91d8-11e9-9012-02684982e60b.gif)

## Storybook
https://hsds-react.netlify.com/?path=/story/radio--custom

## HS-App (wrong)
Example: https://secure.helpscout.net/settings/beacons/ba662315-1003-4983-9133-0641b60bef51/messaging

![image](https://user-images.githubusercontent.com/2151364/59715031-9d53f780-91d8-11e9-82d3-f1a2cdf1a773.png)

## HSDS (correct)
![image](https://user-images.githubusercontent.com/2151364/59715010-8b725480-91d8-11e9-963c-59f81a617248.png)

**Comment by plbabin** [comment]
fixed in v3 https://github.com/helpscout/hsds-react/tree/v3
