### ISSUE TITLE
Portal: Improve rendering performance (React 16)

### ISSUE THREAD

**Issue by ItsJonQ** [helpscout/hsds-react#653]
The HSDS: React Portal was one of the first (hard) components to have been built. At the time, it was early days of React 15 when the official [React Portal](https://reactjs.org/docs/portals.html) solution wasn't even a thing yet.

The initial implementation was essentially a modified version of this library:
https://github.com/tajo/react-portal

Since then, it has been adjusted/modified to suite our needs.

Fast forward to 2019, with `ReactDOM.createPortal` being a thing, as well as `useRef`, `createContext` and a bunch of other new React 16 goodies... I think it may be about time to update this component.

The reason why I mentioned things like `createContext` and `useRef` is that those features don't translate well to the current Portal implementation ( 😭)

Check out the library mentioned above. They provide a legacy implementation for non-React 16 users.

**Comment by tinkertrain** [comment]
💥  https://github.com/helpscout/hsds-react/pull/866
