### ISSUE TITLE
Component: Settings Block

### ISSUE THREAD

**Issue by jaredmcdaniel** [helpscout/hsds-react#654]
There are a couple issues I'm seeing related to the main settings block from Settings.

#### Example: Manage Beacon > Messages
https://secure.helpscout.net/settings/beacons/a52615d2-af20-45a3-beb1-c67afbe4d592/messaging

## 1. Incorrect margin between multiple blocks.
Currently there is a 40px margin between blocks. It should be 20px.

**Current:**

![image](https://user-images.githubusercontent.com/2151364/60273936-cbae9280-98bc-11e9-8cf1-ac16d80ac76a.png)

**Should be:**

![image](https://user-images.githubusercontent.com/2151364/60273986-dd903580-98bc-11e9-8505-131226b8a451.png)

## 2. Incorrect margin above button group actions "footer"
Currently it is 40px. It should be 30px.

**Current:**

![image](https://user-images.githubusercontent.com/2151364/60273831-92762280-98bc-11e9-86d9-06827aca78da.png)

**Should be:**

![image](https://user-images.githubusercontent.com/2151364/60273868-a9b51000-98bc-11e9-8357-d42c09f519a3.png)

**Comment by tinkertrain** [comment]
Fixed at some point? There has been lots of updates for these here and in HS App, if still present we'll reopen
