### ISSUE TITLE
Component: Input w/ nested Button overlaps in Firefox

### ISSUE THREAD

**Issue by ryan-mulrooney** [helpscout/hsds-react#669]
This appears to be an issue in Firefox only. An <Input> with an action with display an overlapped button **if** the input width is too narrow. This is due to there being a default `min-width: auto` on inputs. To fix it a `min-width: 0` should be applied to the input. @tinkertrain suggested only adding this style conditionally if there is a nested button (to reduce the potential of breaking the input elsewhere).

**Current issue:** http://c.hlp.sc/44a3671588ae

**With fix applied:** http://c.hlp.sc/56a7d8a743c1

**Comment by plbabin** [comment]
that seems to have been resolve under v3: https://hsds.helpscout.com/?path=/story/%F0%9F%A7%AC-components-forms-input--actions.
