### ISSUE TITLE
Bug 🐛: Link to Components under Quick start in docs TOC is broken 

### ISSUE THREAD

**Issue by abdusabri** [helpscout/hsds-react#899]
In the Docs Table of Contents, the link to Components under Quick start is broken (https://github.com/helpscout/hsds-react/blob/master/docs/README.md)

![image](https://user-images.githubusercontent.com/25670682/103476186-35fe9800-4dbc-11eb-88f3-3c5d5f87c08e.png)

![image](https://user-images.githubusercontent.com/25670682/103476188-37c85b80-4dbc-11eb-9471-e8e8cb634104.png)

I tried to figure out what the correct link should be to open a PR with a fix, but I couldn't 😊.

Note: I've added "Bug 🐛" to the title of the issue until a core team member adds a label 🙈

**Comment by plbabin** [comment]
Thank you, the quick start link has been removed from the doc in d8dbcd7230be202909becd999dbccf6569989eef
